### ISSUE TITLE
Implement return for painted products

### ISSUE THREAD

**Issue by parqaman** [GBT-Developer/warehouse-management-system#35]
In this page user has the ability to create a special "surat jalan" to return a product due to lack of painting's quality in one or many products.

Input fields needed:

- [x] Choose the existing "surat jalan"
- [x] Choose the products from the chosen "surat jalan"
- [x] Create or generate "surat jalan" for painted item return
- [x] Update status back to "sedang dalam pengecatan"

**Comment by BernhardRicardo** [comment]
return process has changed. If products didn't pass QC, it will be marked as broken product.

bug fixed by farouq on checkBrokenProducts function
